config/routes.rb
ProgrammingWisdom::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  resources :quotes do
    collection do
      get 'authors'
    end
  end

  root 'quotes#index'

  

end

app/models/author.rb
class Author < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :author
  validate :possible_duplicated_quote

  def author_name
    author ? author.name : ''
  end

  def possible_duplicated_quote
    longest_word = self.text.gsub(/[!?;,.]/, '').split.group_by(&:size).max.last
    @possible_quotes = Quote.basic_search(longest_word)

    @possible_quotes.each do |quote|
      distance = Text::Levenshtein.distance(text, quote.text)
      if distance < self.text.size / 8
        errors.add(:text, "possibly duplicated to another quote (distance = #{distance}): #{quote.text}")
        break
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :token_authenticatable, :registerable

  # Setup accessible (or protected) attributes for your model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :authors]

  def authenticate_user!
    redirect_to "/", alert: 'You dont have enough permissions to be here' unless user_signed_in?
  end

  def quote_params
    params.require(:quote).permit(:text, :author, :source)
  end

  # GET /quotes
  # GET /quotes.json
  def index
    if q = params[:q]
      @quotes = Quote.basic_search(q)
    else
      @quotes = Quote.order("updated_at DESC")
    end
    @quotes = @quotes.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    update_author(@quote)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])
    update_author(@quote)

    respond_to do |format|
      if @quote.update_attributes(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  def authors
    authors = (term = params[:q]) ? Author.basic_search(term) : Author.all
    render json: authors.map(&:name)
  end

  private

  def update_author(quote)
    quote.author = Author.where(name: params[:quote][:author_name]).first_or_create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name)
    content_tag(:i, nil, class: "icon-#{name}")
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/application/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'programmingwisdom'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/application/_navbar.html.slim
.navbar
  .navbar-inner
    a.brand(href="/") Programming Wisdom
    = form_tag('/quotes', method: 'get', class: 'navbar-search') do
      input.search-query(type="text" name="q" placeholder="Search Quote")
    ul.nav.pull-right
      - if user_signed_in?
        li= link_to 'Sign-out', destroy_user_session_path, :method => :delete
      - else
        li= link_to 'Sign-in', user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Programming Wisdom
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'navbar'
    .container
      - if notice
        .notice= notice
      - if alert
        .alert= alert
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Programming Wisdom
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = render 'navbar'
    .container
      - if notice
        .alert.alert-success= notice
      - if alert
        .alert= alert
      = yield

app/views/quotes/_form.html.haml
= form_for(@quote) do |f|
  - if @quote.errors.any?
    #error_explanation
      %h2
        = pluralize(@quote.errors.count, "error")
        prohibited this quote from being saved:
      %ul
        - @quote.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :text
    = f.text_area :text, rows: 5, class: 'input-wide'
  .field
    = f.label :author
    = f.text_field :author, class: 'input-wide'
  .field
    = f.label :source
    = f.text_field :source, class: 'input-wide'
  .actions
    = f.submit class: 'btn btn-primary'

app/views/quotes/_form.html.slim
= form_for(@quote) do |f|
  - if @quote.errors.any?
    #error_explanation
      h2
        = pluralize(@quote.errors.count, "error")
        |  prohibited this quote from being saved:
      ul
        - @quote.errors.full_messages.each do |msg|
          li= msg
  .field
    = f.label :text
    = f.text_area :text, rows: 5, class: 'input-wide'
  .field
    = f.label :author
    = f.text_field :author_name, class: 'input-wide'
  .field
    = f.label :source
    = f.text_field :source, class: 'input-wide'
  .actions
    = f.submit class: 'btn btn-primary'
coffee:
  $ ->
    $('#quote_author_name').typeahead
      source: (query, process) ->
        $.get '/quotes/authors', { q: query }, (data) ->
          process data

app/views/quotes/_quote.html.haml
.quote.row
  .quote-details.span11
    .quote-text
      #{quote.text}
    .quote-author
      - if quote.author
        = quote.author.name
      - unless quote.source.blank?
        , #{quote.source}
  - if user_signed_in?
    .actions
      = link_to 'Edit', edit_quote_path(quote), class: 'btn'
  .quoteFooter

app/views/quotes/_quote.html.slim
.quote.row
  .quote-details
    .quote-text
      = quote.text
    .quote-author
      - if quote.author
        = quote.author.name
      - unless quote.source.blank?
        | , from&nbsp;
        span.quote-source= quote.source
  - if footer
    .quoteFooter
      = link_to icon('comment'), quote
      - if user_signed_in?
        = link_to icon('edit'), edit_quote_path(quote)

app/views/quotes/edit.html.haml
%h1 Editing quote
= render 'form'

.btn-group
  = link_to 'Show', @quote, class: 'btn btn-small'
  = link_to 'Delete', @quote, method: :delete, class: 'btn btn-small', confirm: 'Are you sure?'
  = link_to 'Back', quotes_path, class: 'btn btn-small'

app/views/quotes/edit.html.slim
h1 Editing quote
= render 'form'

.btn-group
  = link_to 'Show', @quote, class: 'btn btn-small'
  = link_to 'Delete', @quote, method: :delete, class: 'btn btn-small', data: {confirm: 'Are you sure?'}
  = link_to 'Back', quotes_path, class: 'btn btn-small'

app/views/quotes/index.html.haml
- if user_signed_in?
  .actions.btn-group
    = link_to 'New Quote', new_quote_path, class: 'btn'
.quotes
  - @quotes.each do |quote|
    = render quote

app/views/quotes/index.html.slim
- if user_signed_in?
  .actions.btn-group
    = link_to 'New Quote', new_quote_path, class: 'btn btn-primary'
.quotes
  = paginate @quotes, :window => 9
  - @quotes.each do |quote|
    = render :partial => 'quote', :locals => {:quote => quote, :footer => true}

app/views/quotes/new.html.haml
%h1 New quote
= render 'form'

.btn-group
  = link_to 'Back', quotes_path, class: 'btn btn-small'

app/views/quotes/new.html.slim
h1 New quote
= render 'form'

.btn-group
  = link_to 'Back', quotes_path, class: 'btn btn-small'

app/views/quotes/show.html.slim
- if user_signed_in?
  .actions.btn-group
    = link_to 'New Quote', new_quote_path, class: 'btn btn-primary'
= render :partial => @quote, :locals => {:quote => @quote, :footer => false}
br
= render :partial => 'disqus'